version: '3.3'

services:
  salary_api:
    volumes:
      - salary_db:/salary_api/salary_db/  
    build: ../
    restart: always
    ports:
      - 8000:8000
    env_file:
      - ./.env

volumes:
  salary_db:

