"""ammend user

Revision ID: 851f8b1f117a
Revises: 44c8ac3ed05c
Create Date: 2023-06-03 18:32:00.554546

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '851f8b1f117a'
down_revision = '44c8ac3ed05c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
